## Saving and sharing your numpy arrays

In [2]:
# Create your arrays

# Now that you have imported the numpy library, you can make a couple of arrays lets start with two 1d arrays, x and y, where y=x*82 you will assign x to the integers from 0 to 9 using np.arange
import numpy as np
x = np.arange(10)
y = x ** 2
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


## Save your arrays with numpy's savez

In [3]:
# The first thing you will do is save them to a file as zipped arrays using savez. You will use two options to labesl the arrays in the file

x_axis = x # this option is assigning the name x_axis to the variable x
y_axis = y # this optionn is assiging the  name y_axis to the variable y


np.savez("x_y-squared.npz", x_axis=x, y_axis=y)

## Remove the saved arrays and load them back with numpy's load

In [4]:
# In your current working directory , you shoudl have a new file with the name x_y-squared.npz. The file is a zipped binary of the two arrays, x and y. Lets clear the workspace and load the values back in .This x_y-squared.npz file contains two NPY format files. The NPY format is a native binary format. You cannot read the numbers in a standard text editor or spreadsheet

del x, y

In [5]:
# To see what variables are in the workspace, use the jupyter magic command whos


%whos

Variable   Type       Data/Info
-------------------------------
np         module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
x_axis     ndarray    10: 10 elems, type `int64`, 80 bytes
y_axis     ndarray    10: 10 elems, type `int64`, 80 bytes


In [6]:
load_xy =  np.load('x_y-squared.npz')
print(load_xy.files)

['x_axis', 'y_axis']


In [7]:
whos

Variable   Type       Data/Info
-------------------------------
load_xy    NpzFile    <numpy.lib.npyio.NpzFile <...>object at 0x7f59580ba210>
np         module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
x_axis     ndarray    10: 10 elems, type `int64`, 80 bytes
y_axis     ndarray    10: 10 elems, type `int64`, 80 bytes


## Reassign the NpzFile arrays to x and y

In [8]:
# You have now created the dictionary with an NpzFile type. the included files are x_axis and y_axis that you defined in your savez command. You can reassign x and y to the load_xy files.


x = load_xy["x_axis"]
y = load_xy["y_axis"]
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


## Another option: saving to human-readable csv

In [9]:
# Lets consider another scenario, you want to share x and y with other people or other programs. You may need human-readable text file that is easier to share. Next you use the savetxt to save x and y in a comma separated value file, x_y-squared.csv. The resulting csv is composed of ASCII characters. You can load the file back into numpy or read it with other programs.




## Rearrange the data into a single 2D array

In [10]:
# First you have to create a single 2D array from your two 1D arrays. The csv-filetype is a spreadsheet-style dataset. The csv arranges numbers in rows-separated by new lines - and columns-separated by commas. If the data is more complex eg multiple 2D arrays or higher dimensional arrays.It is better to use savez. Here you use two numpy functions to format the data:


# 1. np.block : this function appends arrays together into a 2D array
# 2. np.newaxis: this function forces the 1D array into a 2D column vector with 10 rows and 1 column

In [11]:
array_out = np.block([x[:,np.newaxis], y[:, np.newaxis]])
print("the output array has shape", array_out.shape, " with values")
print(array_out)

the output array has shape (10, 2)  with values
[[ 0  0]
 [ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]
 [ 5 25]
 [ 6 36]
 [ 7 49]
 [ 8 64]
 [ 9 81]]


In [12]:
# Then save the data to csv file using savetxt

np.savetxt("x_y-squared.csv",X=array_out, header='x, y', delimiter=',')

In [13]:
# Our arrays as a csv file

del x, y

In [14]:
load_xy = np.loadtxt("x_y-squared.csv",delimiter=",")
load_xy.shape

(10, 2)

In [15]:
x = load_xy[:,0]
y = load_xy[:,1]
print(x)
print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [16]:
# When the arrays are saved to the csv file, it didnt preserve the int type.When loading the arrays back into your workspace the defaul process will be to load the csv file as a 2D floating point array eg load_xy.dtype == 'float64' and load_xy.shape == (10, 2)